/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.calculator_app_adrian_ziebowski;

/**
 *
 * @author adrik
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        az_jButton7 = new javax.swing.JButton();
        az_jButton8 = new javax.swing.JButton();
        az_jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        az_jButton4 = new javax.swing.JButton();
        az_jButton5 = new javax.swing.JButton();
        az_jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        az_jButton1 = new javax.swing.JButton();
        az_jButton2 = new javax.swing.JButton();
        az_jButton3 = new javax.swing.JButton();
        az_jButtonMnoz = new javax.swing.JButton();
        az_jButton0 = new javax.swing.JButton();
        az_jButtonDziel = new javax.swing.JButton();
        az_jButtonEquals = new javax.swing.JButton();
        az_jButton10 = new javax.swing.JButton();
        az_jButton11 = new javax.swing.JButton();
        az_jButton12 = new javax.swing.JButton();
        az_jButton13 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        az_jButtonClear = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jButton9.setText("-");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);
        setSize(new java.awt.Dimension(278, 456));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jTextField2.setBackground(new java.awt.Color(51, 51, 51));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));

        az_jButton7.setBackground(new java.awt.Color(51, 51, 51));
        az_jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        az_jButton7.setForeground(new java.awt.Color(255, 255, 255));
        az_jButton7.setText("7");
        az_jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButton7ActionPerformed(evt);
            }
        });

        az_jButton8.setBackground(new java.awt.Color(51, 51, 51));
        az_jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        az_jButton8.setForeground(new java.awt.Color(255, 255, 255));
        az_jButton8.setText("8");
        az_jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButton8ActionPerformed(evt);
            }
        });

        az_jButton9.setBackground(new java.awt.Color(51, 51, 51));
        az_jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        az_jButton9.setForeground(new java.awt.Color(255, 255, 255));
        az_jButton9.setText("9");
        az_jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButton9ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        az_jButton4.setBackground(new java.awt.Color(51, 51, 51));
        az_jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        az_jButton4.setForeground(new java.awt.Color(255, 255, 255));
        az_jButton4.setText("4");
        az_jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButton4ActionPerformed(evt);
            }
        });

        az_jButton5.setBackground(new java.awt.Color(51, 51, 51));
        az_jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        az_jButton5.setForeground(new java.awt.Color(255, 255, 255));
        az_jButton5.setText("5");
        az_jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButton5ActionPerformed(evt);
            }
        });

        az_jButton6.setBackground(new java.awt.Color(51, 51, 51));
        az_jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        az_jButton6.setForeground(new java.awt.Color(255, 255, 255));
        az_jButton6.setText("6");
        az_jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButton6ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("-");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        az_jButton1.setBackground(new java.awt.Color(51, 51, 51));
        az_jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        az_jButton1.setForeground(new java.awt.Color(255, 255, 255));
        az_jButton1.setText("1");
        az_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButton1ActionPerformed(evt);
            }
        });

        az_jButton2.setBackground(new java.awt.Color(51, 51, 51));
        az_jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        az_jButton2.setForeground(new java.awt.Color(255, 255, 255));
        az_jButton2.setText("2");
        az_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButton2ActionPerformed(evt);
            }
        });

        az_jButton3.setBackground(new java.awt.Color(51, 51, 51));
        az_jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        az_jButton3.setForeground(new java.awt.Color(255, 255, 255));
        az_jButton3.setText("3");
        az_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButton3ActionPerformed(evt);
            }
        });

        az_jButtonMnoz.setBackground(new java.awt.Color(51, 51, 51));
        az_jButtonMnoz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        az_jButtonMnoz.setForeground(new java.awt.Color(255, 255, 255));
        az_jButtonMnoz.setText("*");
        az_jButtonMnoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButtonMnozActionPerformed(evt);
            }
        });

        az_jButton0.setBackground(new java.awt.Color(51, 51, 51));
        az_jButton0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        az_jButton0.setForeground(new java.awt.Color(255, 255, 255));
        az_jButton0.setText("0");
        az_jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButton0ActionPerformed(evt);
            }
        });

        az_jButtonDziel.setBackground(new java.awt.Color(51, 51, 51));
        az_jButtonDziel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        az_jButtonDziel.setForeground(new java.awt.Color(255, 255, 255));
        az_jButtonDziel.setText("/");
        az_jButtonDziel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButtonDzielActionPerformed(evt);
            }
        });

        az_jButtonEquals.setBackground(new java.awt.Color(51, 51, 51));
        az_jButtonEquals.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        az_jButtonEquals.setForeground(new java.awt.Color(255, 255, 255));
        az_jButtonEquals.setText("=");
        az_jButtonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButtonEqualsActionPerformed(evt);
            }
        });

        az_jButton10.setBackground(new java.awt.Color(51, 51, 51));
        az_jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        az_jButton10.setForeground(new java.awt.Color(255, 255, 255));
        az_jButton10.setText("%");
        az_jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButton10ActionPerformed(evt);
            }
        });

        az_jButton11.setBackground(new java.awt.Color(51, 51, 51));
        az_jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        az_jButton11.setForeground(new java.awt.Color(255, 255, 255));
        az_jButton11.setText(".");
        az_jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButton11ActionPerformed(evt);
            }
        });

        az_jButton12.setBackground(new java.awt.Color(51, 51, 51));
        az_jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        az_jButton12.setForeground(new java.awt.Color(255, 255, 255));
        az_jButton12.setText("√x");
        az_jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButton12ActionPerformed(evt);
            }
        });

        az_jButton13.setBackground(new java.awt.Color(51, 51, 51));
        az_jButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        az_jButton13.setForeground(new java.awt.Color(255, 255, 255));
        az_jButton13.setText("x²");
        az_jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButton13ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));

        az_jButtonClear.setBackground(new java.awt.Color(51, 51, 51));
        az_jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        az_jButtonClear.setForeground(new java.awt.Color(255, 255, 255));
        az_jButtonClear.setText("C");
        az_jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(az_jButtonMnoz, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(az_jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(az_jButtonDziel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(az_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(az_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(az_jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(az_jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(az_jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(az_jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(az_jButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(az_jButton13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(az_jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(az_jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(az_jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(az_jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(az_jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(az_jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(az_jButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(az_jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(az_jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(az_jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(az_jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(az_jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(az_jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(az_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(az_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(az_jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(az_jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(az_jButtonMnoz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(az_jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(az_jButtonDziel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(az_jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(az_jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(az_jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(az_jButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(az_jButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Zapisuj Historię działań");
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuItem1.setText("Zamknij");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void az_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButton1ActionPerformed
        jTextField2.setText(jTextField2.getText() + "1");
    }//GEN-LAST:event_az_jButton1ActionPerformed

    private void az_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButton2ActionPerformed
        jTextField2.setText(jTextField2.getText() + "2");
    }//GEN-LAST:event_az_jButton2ActionPerformed

    private void az_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButton3ActionPerformed
        jTextField2.setText(jTextField2.getText() + "3");
    }//GEN-LAST:event_az_jButton3ActionPerformed

    private void az_jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButton4ActionPerformed
        jTextField2.setText(jTextField2.getText() + "4");
    }//GEN-LAST:event_az_jButton4ActionPerformed

    private void az_jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButton5ActionPerformed
        jTextField2.setText(jTextField2.getText() + "5");
    }//GEN-LAST:event_az_jButton5ActionPerformed

    private void az_jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButton6ActionPerformed
        jTextField2.setText(jTextField2.getText() + "6");
    }//GEN-LAST:event_az_jButton6ActionPerformed

    private void az_jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButton7ActionPerformed
        jTextField2.setText(jTextField2.getText() + "7");
    }//GEN-LAST:event_az_jButton7ActionPerformed

    private void az_jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButton8ActionPerformed
        jTextField2.setText(jTextField2.getText() + "8");
    }//GEN-LAST:event_az_jButton8ActionPerformed

    private void az_jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButton9ActionPerformed
        jTextField2.setText(jTextField2.getText() + "9");
    }//GEN-LAST:event_az_jButton9ActionPerformed

    private void az_jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButton0ActionPerformed
        jTextField2.setText(jTextField2.getText() + "0");
    }//GEN-LAST:event_az_jButton0ActionPerformed

    private void az_jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButton11ActionPerformed
        jTextField2.setText(jTextField2.getText() + ".");
    }//GEN-LAST:event_az_jButton11ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        num = Double.parseDouble(jTextField2.getText()); 
        obliczenia =1;
        jTextField2.setText(" ");
        jLabel1.setText(num + " + ");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        num = Double.parseDouble(jTextField2.getText()); 
        obliczenia =2;
        jTextField2.setText(" ");
        jLabel1.setText(num + " - ");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void az_jButtonDzielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButtonDzielActionPerformed
        num = Double.parseDouble(jTextField2.getText()); 
        obliczenia =3;
        jTextField2.setText(" ");
        jLabel1.setText(num + " / ");
    }//GEN-LAST:event_az_jButtonDzielActionPerformed

    private void az_jButtonMnozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButtonMnozActionPerformed
        num = Double.parseDouble(jTextField2.getText()); 
        obliczenia =4;
        jTextField2.setText(" ");
        jLabel1.setText(num + " * ");
    }//GEN-LAST:event_az_jButtonMnozActionPerformed

    private void az_jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButton10ActionPerformed
        String add = jTextField2.getText();
        
        double d = Double.parseDouble(add);        
        double procent = 0.01 * d;
        
        jLabel1.setText(" "+procent);
        jTextField2.setText("");
    }//GEN-LAST:event_az_jButton10ActionPerformed

    private void az_jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButton13ActionPerformed
        String add = jTextField2.getText();
        
        double d = Double.parseDouble(add);        
        double potega = d * d;
        
        jLabel1.setText(" "+potega);
        jTextField2.setText("");
    }//GEN-LAST:event_az_jButton13ActionPerformed

    private void az_jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButtonClearActionPerformed
        jLabel1.setText(" ");
        jTextField2.setText(" ");
    }//GEN-LAST:event_az_jButtonClearActionPerformed

    private void az_jButtonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButtonEqualsActionPerformed
        operacje();
    }//GEN-LAST:event_az_jButtonEqualsActionPerformed

    private void az_jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButton12ActionPerformed
        String add = jTextField2.getText();
        
        double d = Double.parseDouble(add);        
        double sqrt = Math.sqrt(d);
        
        jLabel1.setText(" "+sqrt);
        jTextField2.setText("");
    }//GEN-LAST:event_az_jButton12ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }
    
    double num,ans;
    int obliczenia;
    
    
    public void operacje(){
        String text = jTextField2.getText();
        double d = Double.parseDouble(text);
        
        switch(obliczenia){            
        
            case 1: 
                
                ans = num + Double.parseDouble(jTextField2.getText());
                jLabel1.setText(jLabel1.getText()+d+" =");
                jTextField2.setText(Double.toString(ans));
                break;
        
            case 2:                 
                ans = num - Double.parseDouble(jTextField2.getText());
                jLabel1.setText(jLabel1.getText()+d+" =");
                jTextField2.setText(Double.toString(ans));
                break;
                
            case 3:                
                ans = num / Double.parseDouble(jTextField2.getText());
                jLabel1.setText(jLabel1.getText()+d+" =");
                jTextField2.setText(Double.toString(ans));
                break;
                
            case 4:                
                ans = num * Double.parseDouble(jTextField2.getText());
                jLabel1.setText(jLabel1.getText()+d+" =");
                jTextField2.setText(Double.toString(ans));                
                break;
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton az_jButton0;
    private javax.swing.JButton az_jButton1;
    private javax.swing.JButton az_jButton10;
    private javax.swing.JButton az_jButton11;
    private javax.swing.JButton az_jButton12;
    private javax.swing.JButton az_jButton13;
    private javax.swing.JButton az_jButton2;
    private javax.swing.JButton az_jButton3;
    private javax.swing.JButton az_jButton4;
    private javax.swing.JButton az_jButton5;
    private javax.swing.JButton az_jButton6;
    private javax.swing.JButton az_jButton7;
    private javax.swing.JButton az_jButton8;
    private javax.swing.JButton az_jButton9;
    private javax.swing.JButton az_jButtonClear;
    private javax.swing.JButton az_jButtonDziel;
    private javax.swing.JButton az_jButtonEquals;
    private javax.swing.JButton az_jButtonMnoz;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
