/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ziebowski_adrian_rejestracja_i_logowanie_4_14_2021;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Scanner;

/**
 *
 * @author adrik
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        addKeyListenerToaz_jTextFieldUserName();
        password();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        az_jLabelRegister = new javax.swing.JLabel();
        az_jLabelUsername = new javax.swing.JLabel();
        az_jTextFieldUserName = new javax.swing.JTextField();
        az_jLabelEmail = new javax.swing.JLabel();
        az_jTextFieldEmail = new javax.swing.JTextField();
        az_jLabelPassword = new javax.swing.JLabel();
        az_jLabelConfPass = new javax.swing.JLabel();
        az_jButtonRegister = new javax.swing.JButton();
        az_jButtonPolish = new javax.swing.JButton();
        az_jButtonEnglish = new javax.swing.JButton();
        az_jPasswordField2 = new javax.swing.JPasswordField();
        az_jPasswordField3 = new javax.swing.JPasswordField();
        az_jLabelWrong = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        az_jLabelLogin = new javax.swing.JLabel();
        az_jLabelMail = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        az_jLabelPass = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        az_jButtonSingIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        az_jLabelRegister.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        az_jLabelRegister.setText("Rejestracja");

        az_jLabelUsername.setText("Nazwa Użytkownika");

        az_jTextFieldUserName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        az_jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jTextFieldUserNameActionPerformed(evt);
            }
        });

        az_jLabelEmail.setText("E-mail");

        az_jTextFieldEmail.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        az_jLabelPassword.setText("Hasło");

        az_jLabelConfPass.setText("Potwierdz Hasło");

        az_jButtonRegister.setBackground(new java.awt.Color(255, 255, 255));
        az_jButtonRegister.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        az_jButtonRegister.setText("Rejestracja");
        az_jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButtonRegisterActionPerformed(evt);
            }
        });

        az_jButtonPolish.setBackground(new java.awt.Color(102, 102, 102));
        az_jButtonPolish.setForeground(new java.awt.Color(255, 255, 255));
        az_jButtonPolish.setText("Pl");
        az_jButtonPolish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButtonPolishActionPerformed(evt);
            }
        });

        az_jButtonEnglish.setBackground(new java.awt.Color(102, 102, 102));
        az_jButtonEnglish.setForeground(new java.awt.Color(255, 255, 255));
        az_jButtonEnglish.setText("Eng");
        az_jButtonEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                az_jButtonEnglishActionPerformed(evt);
            }
        });

        az_jLabelWrong.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        az_jLabelWrong.setForeground(new java.awt.Color(255, 102, 102));
        az_jLabelWrong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(az_jTextFieldUserName)
                    .addComponent(az_jTextFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(az_jLabelRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 499, Short.MAX_VALUE)
                        .addComponent(az_jButtonEnglish)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(az_jButtonPolish))
                    .addComponent(az_jPasswordField3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(az_jLabelUsername)
                            .addComponent(az_jLabelEmail)
                            .addComponent(az_jLabelPassword)
                            .addComponent(az_jLabelConfPass))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(az_jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(az_jLabelWrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(az_jPasswordField2)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(az_jLabelRegister)
                    .addComponent(az_jButtonPolish)
                    .addComponent(az_jButtonEnglish))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(az_jLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(az_jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(az_jLabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(az_jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(az_jLabelPassword)
                .addGap(60, 60, 60)
                .addComponent(az_jLabelConfPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(az_jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(az_jLabelWrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(az_jButtonRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(212, Short.MAX_VALUE)
                    .addComponent(az_jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(152, 152, 152)))
        );

        jTabbedPane1.addTab("Rejestracja", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        az_jLabelLogin.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        az_jLabelLogin.setText("Logowanie");

        az_jLabelMail.setText("E-mail");

        az_jLabelPass.setText("Hasło");

        az_jButtonSingIn.setBackground(new java.awt.Color(255, 255, 255));
        az_jButtonSingIn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        az_jButtonSingIn.setText("Sing In");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(az_jButtonSingIn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(az_jLabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(az_jLabelMail)
                            .addComponent(az_jLabelPass))
                        .addGap(0, 502, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(az_jLabelLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(az_jLabelMail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(az_jLabelPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(az_jButtonSingIn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Logowanie", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void az_jButtonEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButtonEnglishActionPerformed
        setEnglish();
    }//GEN-LAST:event_az_jButtonEnglishActionPerformed

    private void az_jButtonPolishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButtonPolishActionPerformed
        setPolish();
    }//GEN-LAST:event_az_jButtonPolishActionPerformed

    private void az_jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jTextFieldUserNameActionPerformed
        
    }//GEN-LAST:event_az_jTextFieldUserNameActionPerformed

    private void az_jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_az_jButtonRegisterActionPerformed
        if(az_jTextFieldUserName.getText().length() > 20 || az_jTextFieldUserName.getText().length() < 2)az_jLabelWrong.setText("Długość nazwy użytkownika jest zła (min 2, max 20) popraw to.");    
        Zapis();
    }//GEN-LAST:event_az_jButtonRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    public void setEnglish()
    {
        az_jLabelUsername.setText("Username");
        az_jLabelPassword.setText("Password");
        az_jLabelConfPass.setText("Confirm Password");
        az_jButtonRegister.setText("Registration");
        az_jLabelRegister.setText("Registration");
        az_jLabelLogin.setText("Sing in");
        az_jLabelPass.setText("Password");
        az_jButtonSingIn.setText("Sing in");
        if(az_jLabelWrong.getText().length() > 2) az_jLabelWrong.setText("Your username length is valid (min 2, max 20) change this!");
    }
    
    public void setPolish()
    {
        az_jLabelUsername.setText("Nazwa użytkownika");
        az_jLabelPassword.setText("Hasło");
        az_jLabelConfPass.setText("Potwierdz Hasło");
        az_jButtonRegister.setText("Rejestracja");
        az_jLabelRegister.setText("Rejestracja");
        az_jLabelLogin.setText("Logowanie");
        az_jLabelPass.setText("Hasło");
        az_jButtonSingIn.setText("Logowanie");
        if(az_jLabelWrong.getText().length() > 2) az_jLabelWrong.setText("Długość nazwy użytkownika jest zła (min 2, max 20) popraw to.");
    }   
    
    
        private void Zapis(){
        try{
        
            File f = new File("zapis.txt");
            FileWriter fw = new FileWriter(f);
            
            String a = az_jTextFieldUserName.getText();
            String b = az_jTextFieldEmail.getText();
            char[] c = az_jPasswordField2.getPassword();            
            char[] e = az_jPasswordField3.getPassword();
            
            String g = jTextField1.getText();
            String h = jTextField2.getText();            

            fw.write("Name: "+a);
            fw.write("\nEmail: "+b);
            fw.write("\nPassword: "+Arrays.toString(c));
            fw.write("\nConfirm Password: "+Arrays.toString(e));
            fw.write("\n");
            fw.write("\nLogin: "+g);
            fw.write("\nPass: "+h);                        
            fw.close();
        
        }catch(IOException e){
            System.out.println("BŁĄD");
        }
    }  
        
    private void addKeyListenerToaz_jTextFieldUserName(){
        az_jTextFieldUserName.addKeyListener(new KeyListener() {
            @Override            
            public void keyTyped(KeyEvent e){
                String temp = az_jTextFieldUserName.getText();
                char ch = e.getKeyChar();
                if((ch >= 'a' && ch <= 'z' || ch>= 'A' && ch<= 'Z' || ch==KeyEvent.VK_BACK_SPACE) &&
                        (temp.length() < 20 || temp.length() > 2 || ch==KeyEvent.VK_BACK_SPACE)){
                    az_jTextFieldUserName.setEditable(true);             
                }else{
                    az_jTextFieldUserName.setEditable(false);
                }
            }
            @Override
            public void keyPressed(KeyEvent e) {
                
            }
            @Override
            public void keyReleased(KeyEvent e) {

            }
        });
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton az_jButtonEnglish;
    private javax.swing.JButton az_jButtonPolish;
    private javax.swing.JButton az_jButtonRegister;
    private javax.swing.JButton az_jButtonSingIn;
    private javax.swing.JLabel az_jLabelConfPass;
    private javax.swing.JLabel az_jLabelEmail;
    private javax.swing.JLabel az_jLabelLogin;
    private javax.swing.JLabel az_jLabelMail;
    private javax.swing.JLabel az_jLabelPass;
    private javax.swing.JLabel az_jLabelPassword;
    private javax.swing.JLabel az_jLabelRegister;
    private javax.swing.JLabel az_jLabelUsername;
    private javax.swing.JLabel az_jLabelWrong;
    private javax.swing.JPasswordField az_jPasswordField2;
    private javax.swing.JPasswordField az_jPasswordField3;
    private javax.swing.JTextField az_jTextFieldEmail;
    private javax.swing.JTextField az_jTextFieldUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
